package org.parasol.model.audit;

public enum AuditEventType {
	INITIAL_MESSAGES_CREATED,
	LLM_INTERACTION_COMPLETE,
	LLM_INTERACTION_FAILED,
	LLM_RESPONSE_RECEIVED,
	TOOL_EXECUTED,
	INPUT_GUARDRAIL_EXECUTED,
	OUTPUT_GUARDRAIL_EXECUTED
}
